T4T-691 Able Player show/hide button on the resource page.
SmarterApp/DL_DigitalLibrary2.0 pull request #353
Opened 2021-03-17 15:35 UTC by jim-ruhl-accenture-com

2021-03-23 15:03 UTC, JJ-Muller requested changes

2021-03-23 15:03 UTC, JJ-Muller commented on webapp/src/app/resource/components/attachments/card/attachment-card.component.html
> +          A transcript is not available for this video
@jim-ruhl-accenture-com please add a period to the end of the sentence.

2021-03-23 15:10 UTC, jim-ruhl-accenture-com commented on webapp/src/app/resource/components/attachments/card/attachment-card.component.html
> +          A transcript is not available for this video
@JJ-Muller the change is done

2021-03-24 15:46 UTC, JJ-Muller approved these changes

2021-03-24 15:48 UTC, merged