T4T-712 populate the landing page from the API
SmarterApp/DL_DigitalLibrary2.0 pull request #366
Opened 2021-04-20 22:23 UTC by jim-ruhl-accenture-com

Also, the stories 713, 714 and 715 for the actions in the call to action section are included.

2021-04-21 15:57 UTC, JJ-Muller requested changes
@jim-ruhl-accenture-com I am sorry I didn't catch this before, but what do you think about changing the variables that are in the form of "resourceType%" for landing pages instead to "landingType%" form in order to differentiate from landing pages within T4T and the resource pages within T4T.

2021-04-21 16:53 UTC, JJ-Muller requested changes

2021-04-21 16:53 UTC, JJ-Muller commented on webapp/src/app/landing/landing.component.html
> +        <p>{{landingPage.sampleSections.header}}</p>
@jim-ruhl-accenture-com landingPage.sampleSections.header is the value indicated for the header of this section so that it does not have to be hardcoded - see line195

2021-04-21 17:06 UTC, jim-ruhl-accenture-com commented on webapp/src/app/landing/landing.component.html
> +        <p>{{landingPage.sampleSections.header}}</p>
please review this change

2021-04-22 21:37 UTC, JJ-Muller commented on webapp/src/app/landing/landing.component.html
> +        <p>{{landingPage.sampleSections.header}}</p>
@jim-ruhl-accenture-com did you push the commit? I am not seeing the change

2021-04-23 15:41 UTC, jim-ruhl-accenture-com commented on webapp/src/app/landing/landing.component.html
> +        <p>{{landingPage.sampleSections.header}}</p>
The AWS error and the heading fix are done

2021-04-23 22:44 UTC, JJ-Muller approved these changes

2021-04-26 14:10 UTC, merged