T4T-789 - Accessibility &  Instructional resource metadata
SmarterApp/DL_DigitalLibrary2.0 pull request #395
Opened 2021-07-08 23:28 UTC by john-dominguez-accenture

2021-07-09 18:33 UTC, JJ-Muller commented on webapp/package-lock.json
>      "@okta/okta-angular": {
@john-dominguez-accenture are some of these updates related to the vulnerability updates? If so, please strip them back out because we are not prepared to QA those updates in this sprint

2021-07-09 19:14 UTC, john-dominguez-accenture reviewed
resolved

2021-07-09 19:39 UTC, JJ-Muller requested changes

2021-07-09 19:39 UTC, JJ-Muller commented on webapp/src/app/common/controls/tooltip/tooltip.component.html
> -  >Keep Reading<i class="far fa-arrow-right" aria-hidden="true"></i></a>
@john-dominguez-accenture this looks like this change is causing the "Keep Reading" prompt from being displayed when used by the embedded strategy functionality.  see in current behavior that we want to retain: 
![image](https://user-images.githubusercontent.com/33644752/125126129-7dd5e300-e0af-11eb-8670-9db7cbedc94e.png)

2021-07-09 19:39 UTC, JJ-Muller commented on webapp/src/app/resource/components/resource-properties/educational-details.component.html
> +<div *ngIf="isInstructionalResource()">
@john-dominguez-accenture for this addition consider leaving the current educational-details structure the same unless the section is for Accessibility Strategy because it is having an undue effect on the right hand panel section for Interim Connections Playlist where the whole metadata section is not displaying.

2021-07-09 19:39 UTC, JJ-Muller commented on webapp/src/app/resource/playlist/playlist-resource.component.html
> -    <sbdl-educational-details [properties]="resource.properties"></sbdl-educational-details>
@john-dominguez-accenture why was this removed?

2021-07-09 19:39 UTC, JJ-Muller commented on webapp/src/app/resource/strategy/properties/strategy-properties.component.html
> +  <ng-content></ng-content>
@john-dominguez-accenture I don't think we need the subject sections anymore because we are storing and displaying this information within the UAAG Tier element for Accessibility strategies

2021-07-09 19:39 UTC, JJ-Muller commented on webapp/src/app/resource/strategy/properties/strategy-properties.component.scss
> -  @include mdc-ripple-surface;
@john-dominguez-accenture is this why the link cards no longer show on Formative Strategy resources

2021-07-09 19:52 UTC, kb-smarterbalanced commented on webapp/src/app/common/common.module.ts
> +    LinkCardComponent,
remove comma?

2021-07-09 20:09 UTC, kb-smarterbalanced commented on webapp/src/app/common/controls/tooltip/tooltip.component.html
> -  >Keep Reading<i class="far fa-arrow-right" aria-hidden="true"></i></a>
Confirmed - missing

2021-07-09 20:22 UTC, kb-smarterbalanced approved these changes
Other than what Jessica mentioned, this looks good to me.

2021-07-12 17:12 UTC, john-dominguez-accenture commented on webapp/src/app/common/controls/tooltip/tooltip.component.html
> -  >Keep Reading<i class="far fa-arrow-right" aria-hidden="true"></i></a>
Fixed

2021-07-12 19:21 UTC, john-dominguez-accenture commented on webapp/src/app/common/controls/tooltip/tooltip.component.html
> -  >Keep Reading<i class="far fa-arrow-right" aria-hidden="true"></i></a>
Added a function that returns the appropriate  text. It seems like the `this` keyword was out of context by how its called in this generated content.

2021-07-12 19:24 UTC, john-dominguez-accenture commented on webapp/src/app/resource/components/resource-properties/educational-details.component.html
> +<div *ngIf="isInstructionalResource()">
Removed the ngIf on the div and will now check only if the data is loaded and displays it. It is still used for the heading text as it differs between the accessibility and other resources.

2021-07-12 19:25 UTC, john-dominguez-accenture commented on webapp/src/app/resource/playlist/playlist-resource.component.html
> -    <sbdl-educational-details [properties]="resource.properties"></sbdl-educational-details>
This was removed as it was getting passed down in the parent component. This change was reverted to keep the components simpler.

2021-07-12 19:25 UTC, john-dominguez-accenture commented on webapp/src/app/resource/strategy/properties/strategy-properties.component.html
> +  <ng-content></ng-content>
These were removed as i agree with the above statement.

2021-07-12 19:27 UTC, john-dominguez-accenture commented on webapp/src/app/resource/strategy/properties/strategy-properties.component.scss
> -  @include mdc-ripple-surface;
Partially yes, i removed the old css style for the link card being used but forgot to update the formative resource to use the new link card component.

2021-07-12 19:31 UTC, JJ-Muller requested changes

2021-07-12 19:31 UTC, JJ-Muller commented on webapp/src/app/resource/components/resource-card/resource-card.component.scss
> +@import "colors";
@john-dominguez-accenture this just needs to be adjusted to match the styling in figma https://www.figma.com/file/razCwhJMFxJFj9pa7zqY7Z/Tools-for-Teachers-(SP2020)?node-id=10887%3A11476 (log in to inspect) Also see styling in landing.component.scss and .samplePlaylistLIItem inlanding-common.coponent.scss.
You will see the blue border is not actually a solid color but has a water color effect from an image. As well as the title font size needs to be adjusted. thank you!

2021-07-12 19:40 UTC, JJ-Muller commented on webapp/src/app/resource/components/resource-card/resource-card.component.scss
> +@import "colors";
@john-dominguez-accenture additionally the List of Playlists that should show in Instructional resources, are now missing. Should show like: id 1249
![image](https://user-images.githubusercontent.com/33644752/125345920-f9cd6680-e30d-11eb-88e0-9c37efeed6df.png)

2021-07-12 23:15 UTC, john-dominguez-accenture commented
updated
Resource Card
	• Update the icon font-size to 1.5em
	• Update color to blue
	• Formative - Update the icons in the card to use the pDF and youtube icons
	• INTERIM CONNECTIONS PLAYLIST - Revert the resource card changes

2021-07-12 23:22 UTC, john-dominguez-accenture commented on webapp/src/app/resource/components/resource-card/resource-card.component.scss
> +@import "colors";
As per our discussion, resources are only shown if they contain data. If the resource field comes back as an empty object/array, the data will not be shown

2021-07-12 23:56 UTC, JJ-Muller commented on webapp/src/app/resource/components/resource-card/resource-card.component.scss
> +@import "colors";
no action needed, i was looking at a resource in dev that did not have playlists linked so that is why the section did not display. it was a data issue not code

2021-07-13 00:17 UTC, JJ-Muller requested changes
@john-dominguez-accenture last 2 things.  The font size for title in the resource card should be 14.41px (or 0.900625rem).  and the "Learn more..." text should be 13.2px (same size as the "Quick links to the referenced materials." referenced in playlist-resources.component.html).  Thank you!

2021-07-13 00:23 UTC, john-dominguez-accenture commented
> @john-dominguez-accenture last 2 things. The font size for title in the resource card should be 14.41px (or 0.900625rem). and the "Learn more..." text should be 13.2px (same size as the "Quick links to the referenced materials." referenced in playlist-resources.component.html). Thank you!

fixed

2021-07-13 17:02 UTC, JJ-Muller approved these changes

2021-07-13 20:17 UTC, merged