T4T-789 - Show instructional remote framework data from response
SmarterApp/DL_DigitalLibrary2.0 pull request #401
Opened 2021-07-15 23:20 UTC by john-dominguez-accenture

2021-07-15 23:33 UTC, kb-smarterbalanced approved these changes
Looks good

2021-07-15 23:40 UTC, kb-smarterbalanced commented
I approved too quickly - should roll back - needs a fix.

2021-07-16 14:55 UTC, JJ-Muller commented on webapp/src/app/data/mock-data.ts
>      act: '<p>Students can act on their peers&rsquo; comments/questions through written responses. The teacher should act accordingly as they interprets the questions, comments, and discussions at eac
@john-dominguez-accenture  the remote framework section only applies to instructional resources and will not be reflected in the other resource types.

2021-07-16 14:58 UTC, JJ-Muller commented on webapp/src/app/resource/instructional/instructional-remote/instructional-remote.component.html
>    icon="goal"
@john-dominguez-accenture is there any mapping that exists between the icons and the resource types already in the code? Because the icon "goal" here is based on the resource type of the resource, ie. professional learning resources are associated with the goal icon vs. instructional resources are associated with the stair icon.

2021-07-16 15:02 UTC, JJ-Muller requested changes
@john-dominguez-accenture  see comments and the local build failed:
 InstructionalPlaylistsComponent
HeadlessChrome 78.0.3882 (Windows 10.0.0) InstructionalRemoteComponent should create FAILED
        TypeError: Cannot read property 'id' of undefined

2021-07-16 17:05 UTC, john-dominguez-accenture commented on webapp/src/app/resource/instructional/instructional-remote/instructional-remote.component.html
>    icon="goal"
> @john-dominguez-accenture see comments and the local build failed:
> InstructionalPlaylistsComponent
> HeadlessChrome 78.0.3882 (Windows 10.0.0) InstructionalRemoteComponent should create FAILED
> TypeError: Cannot read property 'id' of undefined

Error fixed

2021-07-16 17:08 UTC, john-dominguez-accenture commented on webapp/src/app/data/mock-data.ts
>      act: '<p>Students can act on their peers&rsquo; comments/questions through written responses. The teacher should act accordingly as they interprets the questions, comments, and discussions at eac
Correct. This is for mocking data, as the 'remoteFramework' field was added to the resource, it expects it ( else it will complain that its missing a required field). This file, `mock-data.ts` is only used for our tests.

2021-07-16 17:17 UTC, john-dominguez-accenture commented on webapp/src/app/resource/instructional/instructional-remote/instructional-remote.component.html
>    icon="goal"
There is an icon specific component that does just that, `sbdl-resource-type-icon`. I have updated the the remote component to use `sbdl-resource-type-icon` instead of hardcoding the `goal` icon.

2021-07-16 17:19 UTC, john-dominguez-accenture commented
> @john-dominguez-accenture see comments and the local build failed:
> InstructionalPlaylistsComponent
> HeadlessChrome 78.0.3882 (Windows 10.0.0) InstructionalRemoteComponent should create FAILED
> TypeError: Cannot read property 'id' of undefined

Issue fixed. It was an issue with karma running the component directly, and since it has no data, the fields were all undefined, causing this issue. An ngIf directive was added to the card component to prevent this.

2021-07-16 17:42 UTC, JJ-Muller commented on webapp/src/app/data/mock-data.ts
>      act: '<p>Students can act on their peers&rsquo; comments/questions through written responses. The teacher should act accordingly as they interprets the questions, comments, and discussions at eac
@john-dominguez-accenture though I see, similarly for example, that the "listConnectionsPlaylists" field is not needed in the other resource types teasers as it is only for instructional resources.

2021-07-16 18:13 UTC, john-dominguez-accenture commented on webapp/src/app/data/mock-data.ts
>      act: '<p>Students can act on their peers&rsquo; comments/questions through written responses. The teacher should act accordingly as they interprets the questions, comments, and discussions at eac
I abstracted away the `remoteFramework` field from the `Resource` model, as this is shared with all Resources. `remoteFramework` is now only accessible through the `InstructionalResource` model.

2021-07-27 23:49 UTC, JJ-Muller requested changes
I am not sure what happened, but now the playlist section is not showing up below the remote framework section. See to compare:
http://localhost:4200/resource/134
https://qa.webapp.dl.smarterbalanced.org/resource/134
but it does for another resource...:
http://localhost:4200/resource/126
https://qa.webapp.dl.smarterbalanced.org/resource/126

2021-07-27 23:49 UTC, JJ-Muller commented on webapp/src/app/resource/instructional/instructional-remote/instructional-remote.component.html
> +  description="{{ remoteFramework.title }} (opens in a new window)"
Add back in icon="goal" please.  Expectation was that the icon would be identified by resource type of the resource that is indicated within the remoteFramework section in the resource object, but due to time constraint, let's hardcode the icon for now. It is unlikely to NOT be a PLR.  Thank you

2021-07-30 20:41 UTC, JJ-Muller approved these changes

2021-07-30 21:24 UTC, merged