Feature/t4 t 1142 science search
SmarterApp/DL_DigitalLibrary2.0 pull request #548
Opened 2022-11-03 20:55 UTC by kb-smarterbalanced

For story: https://smarterbalanced.atlassian.net/browse/T4T-1142

2022-11-08 23:45 UTC, JJ-Muller requested changes

2022-11-08 23:45 UTC, JJ-Muller commented on webapp/src/app/data/search/search-request.model.ts
>      DCIStrand: string[];
Search parameter is DciStrand instead of DCIStrand

2022-11-09 00:19 UTC, JJ-Muller requested changes

2022-11-09 00:19 UTC, JJ-Muller commented on webapp/src/app/search/search.component.html
> +    <h3>PerformanceExpectations</h3>
A space is missing between Performance Expectations

2022-11-09 20:22 UTC, kb-smarterbalanced commented on webapp/src/app/data/search/search-request.model.ts
>      DCIStrand: string[];
Fixed

2022-11-09 23:54 UTC, kb-smarterbalanced commented on webapp/src/app/search/search.component.html
> +    <h3>PerformanceExpectations</h3>
This is also fixed now - thanks for the catch!

2022-11-10 14:52 UTC, JJ-Muller approved these changes

2022-11-10 15:56 UTC, merged