Feature/t4 t 1240 uat science search
SmarterApp/DL_DigitalLibrary2.0 pull request #567
Opened 2022-12-13 19:08 UTC by kb-smarterbalanced

2022-12-13 19:08 UTC, kb-smarterbalanced commented
This is for: https://smarterbalanced.atlassian.net/browse/T4T-1240

2022-12-15 17:01 UTC, JJ-Muller requested changes

2022-12-15 18:54 UTC, kb-smarterbalanced commented on webapp/src/app/data/search/search.service.ts
> +      dciStrands: res.dciStrands.map(ds => ({ code: ds.code, title: ds.code.toUpperCase() + ' ' + ds.description })),
This is where the label for the filters is created, I changed it so it uses the shortDescription instead of code.toUpperCase() does that work?

2022-12-15 18:59 UTC, kb-smarterbalanced commented on webapp/src/app/data/search/search.service.ts
> +      dciStrands: res.dciStrands.map(ds => ({ code: ds.code, title: ds.code.toUpperCase() + ' ' + ds.description })),
Ok, I get what you were saying now, this was on the spreadsheet that we would do it, I'm good with either way, since it's there let's just leave it?

2022-12-19 16:54 UTC, JJ-Muller commented on webapp/src/app/data/search/search.service.ts
> +      dciStrands: res.dciStrands.map(ds => ({ code: ds.code, title: ds.code.toUpperCase() + ' ' + ds.description })),
i agree @kb-smarterbalanced let's leave it

2022-12-20 03:01 UTC, merged